id: P44AF562A
initial_creation_type: input
source_metadata:
  Title: Vinaya Sutra
  Editor: P.V.Bapat & V.V.Gokhale
  Publisher: K.P.Jayaswal Research Institute
  Place of Publication: Patna
  Year: '1982'
  Vinaya sūtram:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2006'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:16:25.485861'
last_modified_at: '2022-03-08T16:16:25.485869'
